## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [6]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [7]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [8]:
# 方法一
from sklearn.model_selection import train_test_split
import pandas as pd
data_1_X = X[:40]
data_1_y = y[:40]
data_0_X = X[40:]
data_0_y = y[40:]
data_1_X_train, data_1_X_test, data_1_y_train, data_1_y_test = train_test_split(data_1_X, data_1_y, test_size = 0.25, random_state=42)
data_0_X_train, data_0_X_test, data_0_y_train, data_0_y_test = train_test_split(data_0_X, data_0_y, test_size = 1/16, random_state=42)

# pd.concat([data_1_y_train, data_0_y_train], axis = 0)

data = pd.DataFrame(np.append(data_0_X_test, data_1_X_test, axis=0))
data['y'] = pd.Series(np.append(data_1_y_test, data_0_y_test))

In [9]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [10]:
# 方法二
X1_train, X1_test, y1_train, y1_test = train_test_split(X[:40], y[:40], test_size=10, random_state=42)
X2_train, X2_test, y2_train, y2_test = train_test_split(X[40:], y[40:], test_size=10, random_state=42)
y_test = np.concatenate((y1_test, y2_test))

In [11]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])